#!/bin/bash
clear

# Mengambil nilai domain dan token dari file
domain=$(cat /root/domain)
token=$(cat /root/token.json | jq -r .access_token)

# Meminta input pengguna
read -rp "User: " -e user
read -rp "ID Telegram: " -e telegram
read -p "Expired (biarkan kosong atau tekan saja enter jika tidak butuh masa aktif): " masaaktif

if [ -n "$masaaktif" ]; then
    exp="$(date -d "${masaaktif} days" +"%s")"
    exp2=$(date -d "${masaaktif} days" +"%Y-%m-%d")
else
    exp=0
    exp2=AlwaysON
fi
read -rp "Quota (GB): " -e gb

# Menampilkan opsi reset data
echo "Pilih jenis skilus reset data:"
echo "1. Tanpa ada reset"
echo "2. Harian"
echo "3. Mingguan"
echo "4. Bulanan"
echo "5. Tahunan"

# Menerima input pilihan pengguna
read -p "Masukkan nomor pilihan Anda: " choice

# Memilih strategi reset berdasarkan pilihan pengguna
case $choice in
    1)
        reset_strategy="no_reset"
        ;;
    2)
        reset_strategy="day"
        ;;
    3)
        reset_strategy="week"
        ;;
    4)
        reset_strategy="month"
        ;;
    5)
        reset_strategy="year"
        ;;
    *)
        echo "Pilihan tidak valid."
        exit 1
        ;;
esac

# Menghitung batas kuota dalam bytes
limitq=$((gb * 1024**3))

# Menggunakan variable uuid untuk generate password
uuid=$(cat /proc/sys/kernel/random/uuid)

# Mengirimkan permintaan ke API
curl -X 'POST' \
  "https://${domain}/api/user" \
  -H 'accept: application/json' \
  -H "Authorization: Bearer ${token}" \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "'"${user}"'",
  "proxies": {
    "vless": {
      "id": "'"${uuid}"'",
      "flow": "xtls-rprx-vision"
    }
  },
  "inbounds": {
    "vless": [
      "VLESS_REALITY_FALLBACK",
      "VLESS_REALITY_GRPC"
    ]
  },
  "expire": '"${exp}"',
  "data_limit": '"${limitq}"',
  "data_limit_reset_strategy": "'"${reset_strategy}"'",
  "status": "active",
  "note": "'"${telegram}"'"
}' > /tmp/${user}_vless.json
subs=$(cat /tmp/${user}_vless.json | jq -r .subscription_url)

# Link VLess
vlesslink0="vless://${uuid}@${domain}:443?security=reality&type=tcp&host=&headerType=&path=&sni=teams.microsoft.com&fp=chrome&pbk=M1PTcxApfZYmc8mbUUdMncKejBxZbjEwHGEl68zjlWU&sid=87ae7e1887f2bd1e&spx=#%28${user}%29%20%5BVLESS%20-%20tcp%5D%20REALITY"
vlesslink4="vless://${uuid}@${domain}:443?security=reality&type=grpc&host=&headerType=serviceName=vless-reality-service&sni=teams.microsoft.com&fp=chrome&pbk=M1PTcxApfZYmc8mbUUdMncKejBxZbjEwHGEl68zjlWU&sid=87ae7e1887f2bd1e&spx=#%28${user}%29%20%5BVLESS%20-%20gRPC%5D%20REALITY"

# Contoh Format Openclash
echo "==--LINGVPN PRESENTS--==
TERIMA KASIH TELAH MEMILIH LAYANAN VPN LINGVPN!
LINK URL/CONFIG UNTUK USER ${user^^} DENGAN EXP ${exp2}
MOHON MELAKUKAN PERPANJANGAN VPN MAKSMIMAL 3 HARI SEBELUM TANGGAL EXPIRED SETIAP BULAN NYA!

DETAIL Keterangan ALPN (HARUS DI SETT!):
1.) TCP: h2, http/1.1
2.) GRPC: h2

DETAIL Port Server (Pilih salah satu, Sesuaikan dengan bug masing masing):
1.) TLS : 443, 8443, 8880

DETAIL AKUN lain lain FLOW, serverName Reality dan serviceName gRPC:

🔑 VLess
a.) Flow TCP & GRPC Reality: xtls-rprx-vision
b.) serviceName GRPC Reality: vless-reality-service

🔑 serverNames Reality yang dapat dipakai
a.) static-web.prod.vidiocdn.com
b.) teams.microsoft.com
c.) sb.scorecardresearch.com
d.) www.spotify.com
e.) graph.instagram.com
f.) sogood.linefriends.com
g.) shopee.co.id
h.) r.koubei.com

Config URL :

-==============================-

1.) VLess-TCP REALITY TLS
${vlesslink0}

2.) VLess-gRPC REALITY TLS 
${vlesslink4}

-==============================-

Format Openclash : 

1.) VLess-TCP REALITY TLS 
- name: VlessReality_${user}
  type: vless
  server: ${domain}
  port: 443
  uuid: ${uuid}
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: static-web.prod.vidiocdn.com
  alpn:
   - h2
   - http/1.1
  reality-opts:
    public-key: M1PTcxApfZYmc8mbUUdMncKejBxZbjEwHGEl68zjlWU
    short-id: 87ae7e1887f2bd1e
  client-fingerprint: chrome

2.) VLess-GRPC REALITY TLS
- name: VLessRGRPC_${user}
  type: vless
  server: ${domain}
  port: 443
  uuid: ${uuid}
  udp: true
  xudp: true
  skip-cert-verify: true
  tls: true
  client-fingerprint: chrome
  servername: www.spotify.com
  network: grpc
  grpc-opts:
    grpc-service-name: vless-reality-service
  reality-opts:
    public-key: M1PTcxApfZYmc8mbUUdMncKejBxZbjEwHGEl68zjlWU
    short-id: 87ae7e1887f2bd1e
  ip-version: dual
  tfo: false
  smux:
    enabled: false

SELALU PATUHI PERATURAN SERVER DAN TERIMA KASIH SUDAH MEMILIH LINGVPN 🙏

CONTACT WA : https://wa.me/6283129611215
TELEGRAM CHANNEL : https://t.me/LingVPN
TELEGRAM GROUP : https://t.me/LingVPN_Group" > "/var/www/html/oc-${user}.conf"
echo -e "### vless $user $exp2" >> /var/lib/marzban/akun-vless.conf
clear
echo -e ""
echo -e "=======-XRAY/VLESS-REALITY======="
echo -e ""
echo -e "Remarks: ${user}"
echo -e "Domain: ${domain}"
echo -e "Quota: ${gb} GB"
echo -e "Reset Quota Strategy: ${reset_strategy}"
echo -e "================================="
echo -e "🔑 Port TLS: 443, 8443, 8880"
echo -e "================================="
echo -e "id: ${uuid}"
echo -e "decryption: none"
echo -e "================================="
echo -e "flow: xtls-rprx-vision"
echo -e "network: tcp/gRPC"
echo -e "gRPC serviceName: vless-reality-service"
echo -e "================================="
echo -e "serverNames: {cek di config}"
echo -e "alpn: "
echo -e "a.) TCP: h2, http/1.1"
echo -e "b.) GRPC: h2"
echo -e "tls: true"
echo -e "================================="
echo -e "PublicKey: M1PTcxApfZYmc8mbUUdMncKejBxZbjEwHGEl68zjlWU"
echo -e "shortIds: 87ae7e1887f2bd1e"
echo -e "client-fingerprint: chrome"
echo -e "allowInsecure: true"
echo -e "================================="
echo -e "Link config: https://${domain}/oc-${user}.conf"
echo -e "================================="
echo -e "Link Subscription : https://${domain}${subs}"
echo -e "================================="
echo -e "Expired On: ${exp2}"
rm -r /tmp/${user}_vless.json
