#!/bin/bash
clear

# Mengambil nilai domain dan token dari file
domain=$(cat /root/domain)
token=$(cat /root/token.json | jq -r .access_token)

# Meminta input pengguna
read -rp "User: " -e user
read -rp "ID Telegram: " -e telegram
read -p "Expired (biarkan kosong atau tekan saja enter jika tidak butuh masa aktif): " masaaktif

if [ -n "$masaaktif" ]; then
    exp="$(date -d "${masaaktif} days" +"%s")"
    exp2=$(date -d "${masaaktif} days" +"%Y-%m-%d")
else
    exp=0
    exp2=AlwaysON
fi
read -rp "Quota (GB): " -e gb

# Menampilkan opsi reset data
echo "Pilih jenis skilus reset data:"
echo "1. Tanpa ada reset"
echo "2. Harian"
echo "3. Mingguan"
echo "4. Bulanan"
echo "5. Tahunan"

# Menerima input pilihan pengguna
read -p "Masukkan nomor pilihan Anda: " choice

# Memilih strategi reset berdasarkan pilihan pengguna
case $choice in
    1)
        reset_strategy="no_reset"
        ;;
    2)
        reset_strategy="day"
        ;;
    3)
        reset_strategy="week"
        ;;
    4)
        reset_strategy="month"
        ;;
    5)
        reset_strategy="year"
        ;;
    *)
        echo "Pilihan tidak valid."
        exit 1
        ;;
esac

# Menghitung batas kuota dalam bytes
limitq=$((gb * 1024**3))

# Menggunakan variable uuid untuk generate password
uuid=$(cat /proc/sys/kernel/random/uuid)

# Mengirimkan permintaan ke API
curl -X 'POST' \
  "https://${domain}/api/user" \
  -H 'accept: application/json' \
  -H "Authorization: Bearer ${token}" \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "'"${user}"'",
  "proxies": {
    "vless": {
      "id": "'"${uuid}"'"
    }
  },
  "inbounds": {
    "vless": [
      "VLESS_WS",
      "VLESS_WS_ANTIADS",
      "VLESS_WS_ANTIPORN"
    ]
  },
  "expire": '"${exp}"',
  "data_limit": '"${limitq}"',
  "data_limit_reset_strategy": "'"${reset_strategy}"'",
  "status": "active",
  "note": "'"${telegram}"'"
}' > /tmp/${user}_vless.json
subs=$(cat /tmp/${user}_vless.json | jq -r .subscription_url)

# Link VLess
vlesslink1="vless://${uuid}@${domain}:443?security=tls&type=ws&host=${domain}&headerType=&path=%2Fvless&sni=&fp=&alpn=http%2F1.1#%28${user}%29%20%5BVLESS%20-%20WS%5D%20TLS"
vlesslink2="vless://${uuid}@${domain}:80?security=none&type=ws&host=${domain}&headerType=&path=%2Fvless#%28${user}%29%20%5BVLESS%20-%20WS%5D%20nonTLS"

# Contoh Format Openclash
echo "==--LINGVPN PRESENTS--==
TERIMA KASIH TELAH MEMILIH LAYANAN VPN LINGVPN!
LINK URL/CONFIG UNTUK USER ${user^^} DENGAN EXP ${exp2}
MOHON MELAKUKAN PERPANJANGAN VPN MAKSMIMAL 3 HARI SEBELUM TANGGAL EXPIRED SETIAP BULAN NYA!

DETAIL Keterangan ALPN (HARUS DI SETT!):
1.) WS: http/1.1

DETAIL Port Server (Pilih salah satu, Sesuaikan dengan bug masing masing):
1.) TLS : 443, 8443, 8880
2.) HTTP/nonTLS : 80, 2082, 2083, 3128, 8080

DETAIL AKUN lain lain, WebSocket, FLOW, serverName Reality dan serviceName GRPC:

🔑 VLess
a.) path WS: /vless atau /enter-your-custom-path/vless
b.) path WS Antiads: /vless-antiads
c.) path WS Anti ADS&PORN: /vless-antiporn

Config URL :

-==============================-

1.) VLess-WS TLS 
${vlesslink1}

2.) VLess-WS nonTLS 
${vlesslink2}

-==============================-

Format Openclash : 

1.) VLess-WS TLS 
- name: VlessWS_${user}
  type: vless
  server: ${domain}
  port: 443
  uuid: ${uuid}
  udp: true
  tls: true
  network: ws
  client-fingerprint: chrome
  servername: ${domain}
  alpn:
   - http/1.1
  skip-cert-verify: true
  ws-opts:
    path: "/vless" #selain path ini ada /vless-antiads atau /vless-antiporn 
    headers:
      Host: ${domain}

2.) VLess-WS nonTLS
- name: VlessWS_${user}
  type: vless
  server: ${domain}
  port: 80
  uuid: ${uuid}
  udp: true
  tls: false
  network: ws
  client-fingerprint: chrome
  alpn:
   - http/1.1
  skip-cert-verify: true
  ws-opts:
    path: "/vless" #selain path ini ada /vless-antiads atau /vless-antiporn
    headers:
      Host: ${domain}

SELALU PATUHI PERATURAN SERVER DAN TERIMA KASIH SUDAH MEMILIH LINGVPN 🙏

CONTACT WA : https://wa.me/6283129611215
TELEGRAM CHANNEL : https://t.me/LingVPN
TELEGRAM GROUP : https://t.me/LingVPN_Group" > "/var/www/html/oc-${user}.conf"
echo -e "### vless $user $exp2" >> /var/lib/marzban/akun-vless.conf
clear
echo -e ""
echo -e "=======-XRAY/VLESS-WS======="
echo -e ""
echo -e "Remarks: ${user}"
echo -e "Domain: ${domain}"
echo -e "Quota: ${gb} GB"
echo -e "Reset Quota Strategy: ${reset_strategy}"
echo -e "================================="
echo -e "🔑 Port TLS: 443, 8443, 8880"
echo -e "🔑 Port nonTLS: 80, 2082, 2083, 3128, 8080"
echo -e "================================="
echo -e "id: ${uuid}"
echo -e "decryption: none"
echo -e "network: ws"
echo -e "================================="
echo -e "path: "
echo -e "a.) WS: /vless atau /enter-your-custom-path-here/vless"
echo -e "alpn: http/1.1"
echo -e "================================="
echo -e "tls:"
echo -e "a.) WS: true (tls), false (nontls)"
echo -e "allowInsecure: true"
echo -e "================================="
echo -e "Link config: https://${domain}/oc-${user}.conf"
echo -e "================================="
echo -e "Link Subscription : https://${domain}${subs}"
echo -e "================================="
echo -e "Expired On: ${exp2}"
rm -r /tmp/${user}_vless.json