#!/bin/bash
clear

# Mengambil nilai domain dan token dari file
domain=$(cat /root/domain)
token=$(cat /root/token.json | jq -r .access_token)

# Meminta input pengguna
read -rp "User: " -e user
read -rp "ID Telegram: " -e telegram
read -p "Expired (biarkan kosong atau tekan saja enter jika tidak butuh masa aktif): " masaaktif

if [ -n "$masaaktif" ]; then
    exp="$(date -d "${masaaktif} days" +"%s")"
    exp2=$(date -d "${masaaktif} days" +"%Y-%m-%d")
else
    exp=0
    exp2=AlwaysON
fi
read -rp "Quota (GB): " -e gb

# Menampilkan opsi reset data
echo "Pilih jenis skilus reset data:"
echo "1. Tanpa ada reset"
echo "2. Harian"
echo "3. Mingguan"
echo "4. Bulanan"
echo "5. Tahunan"

# Menerima input pilihan pengguna
read -p "Masukkan nomor pilihan Anda: " choice

# Memilih strategi reset berdasarkan pilihan pengguna
case $choice in
    1)
        reset_strategy="no_reset"
        ;;
    2)
        reset_strategy="day"
        ;;
    3)
        reset_strategy="week"
        ;;
    4)
        reset_strategy="month"
        ;;
    5)
        reset_strategy="year"
        ;;
    *)
        echo "Pilihan tidak valid."
        exit 1
        ;;
esac

# Menghitung batas kuota dalam bytes
limitq=$((gb * 1024**3))

# Menggunakan variable uuid untuk generate password
uuid=$(cat /proc/sys/kernel/random/uuid)

# Mengirimkan permintaan ke API
curl -X 'POST' \
  "https://${domain}/api/user" \
  -H 'accept: application/json' \
  -H "Authorization: Bearer ${token}" \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "'"${user}"'",
  "proxies": {
     "trojan": {
      "password": "'"${uuid}"'"
    },
	 "vless": {
      "id": "'"${uuid}"'",
      "flow": "xtls-rprx-vision"
    },
	 "vmess": {
      "id": "'"${uuid}"'"
    },
	 "shadowsocks": {
      "password": "'"${uuid}"'",
	  "method": "aes-128-gcm"
    }
  },
  "inbounds": {},
  "expire": '"${exp}"',
  "data_limit": '"${limitq}"',
  "data_limit_reset_strategy": "'"${reset_strategy}"'",
  "status": "active",
  "note": "'"${telegram}"'"
}' > /tmp/${user}_all.json
subs=$(cat /tmp/${user}_all.json | jq -r .subscription_url)

#trojan
trojanlink1="trojan://${uuid}@${domain}:443?security=tls&type=tcp&host=&headerType=&path=&sni=${domain}&fp=&alpn=h2#%20%28${user}%29%20%5BTrojan%20-%20TCP%5D%20TLS"
trojanlink2="trojan://${uuid}@${domain}:443?security=tls&type=ws&host=domain&headerType=&path=%2Ftrojan&sni=domain&fp=&alpn=http%2F1.1#%20%28${user}%29%20%5BTrojan%20-%20WS%5D%20TLS"
trojanlink3="trojan://${uuid}@${domain}:80?security=none&type=ws&host=domain&headerType=&path=%2Ftrojan#%20%28${user}%29%20%5BTrojan%20-%20WS%5D%20nonTLS"
trojanlink4="trojan://${uuid}@${domain}:443?security=tls&type=grpc&host=&headerType=&serviceName=trojan-service&sni=${domain}&fp=&alpn=h2#%20%28${user}%29%20%5BTrojan%20-%20GRPC%5D%20TLS"

#vless
xtls="vless://${uuid}@${domain}:443?security=reality&type=tcp&host=${domain}&headerType=&flow=xtls-rprx-vision&path=&sni=teams.microsoft.com&fp=chrome&pbk=M1PTcxApfZYmc8mbUUdMncKejBxZbjEwHGEl68zjlWU&sid=87ae7e1887f2bd1e&spx=#%28${user}%29%20%5BVLESS%20-%20REALITY%5D"
vlesslink1="vless://${uuid}@${domain}:443?security=tls&type=ws&host=domain&headerType=&path=%2Fvless&sni=&fp=&alpn=http%2F1.1#%20%28${user}%29%20%5BVLESS%20-%20WS%5D%20TLS"
vlesslink2="vless://${uuid}@${domain}:80?security=none&type=ws&host=domain&headerType=&path=%2Fvless#%20%28${user}%29%20%5BVLESS%20-%20WS%5D%20nonTLS"
vlesslink3="vless://${uuid}@${domain}:443?security=tls&type=grpc&host=domain&headerType=&serviceName=vless-service&sni=${domain}&fp=&alpn=h2#%20%28${user}%29%20%5BVLESS%20-%20GRPC%5D%20TLS"

#ss
tmp1=$(echo -n "aes-128-gcm:${uuid}" | base64 -w0)
linkss1="ss://${tmp1}@${domain}:1080#%20%28${user}%29%20%5BShadowsocks%20-%20TCP%5D%20Outline"
linkss2="ss://${tmp1}@${domain}:443?path=%2Fshadowsocks&security=tls&host=domain&type=ws&sni=${domain}#%20%28${user}%29%20%5BShadowsocks%20-%20WS%5D%20TLS"
linkss3="ss://${tmp1}@${domain}:80?path=%2Fshadowsocks&security=&host=domain&type=ws#%20%28${user}%29%20%5BShadowsocks%20-%20WS%5D%20nonTLS"
linkss4="ss://${tmp1}@${domain}:443?path=mode=gun&security=tls&type=grpc&serviceName=shadowsocks-service#%20%28${user}%29%20%5BShadowsocks%20-%20GRPC%5D%20TLS"

#vmess
tls=`cat<<EOF
      {
      "v": "2",
      "ps": "(${user}) [VMess - WS] TLS",
      "add": "domain",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "",
      "tls": "tls"
}
EOF`
none=`cat<<EOF
      {
      "v": "2",
      "ps": "(${user}) [VMess - WS] nonTLS",
      "add": "domain",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "",
      "tls": "none"
}
EOF`
grpc=`cat<<EOF
 {
      "v": "2",
      "ps": "(${user}) [VMess - GRPC] TLS",
      "add": "domain",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "grpc",
      "path": "vmess-service",
      "type": "gun",
      "host": "",
      "tls": "tls"
}
EOF`
tcp=`cat<<EOF
      {
      "v": "2",
      "ps": "(${user}) [VMess - TCP] TLS",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "tcp",
      "path": "/vmess-tcp",
      "type": "http",
      "host": "",
      "tls": "tls"
}
EOF`
tcpnon=`cat<<EOF
      {
      "v": "2",
      "ps": "(${user}) [VMess - TCP] nonTLS",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "tcp",
      "path": "/vmess-tcp",
      "type": "http",
      "host": "",
      "tls": "none"
}
EOF`
vmesslink1="vmess://$(echo $tls | base64 -w 0)"
vmesslink2="vmess://$(echo $none | base64 -w 0)"
vmesslink3="vmess://$(echo $grpc | base64 -w 0)"
vmesslink4="vmess://$(echo $tcp | base64 -w 0)"
vmesslink5="vmess://$(echo $tcpnon | base64 -w 0)"
echo "==--LINGVPN PRESENTS--==
TERIMA KASIH TELAH MEMILIH LAYANAN VPN LINGVPN!
LINK URL/CONFIG UNTUK USER ${user^^} DENGAN KUOTA ${kuota} EXP ${exp2}
MOHON MELAKUKAN PERPANJANGAN VPN MAKSMIMAL 3 HARI SEBELUM TANGGAL EXPIRED SETIAP BULAN NYA!

DETAIL Keterangan ALPN (HARUS DI SETT!):
1.) TCP: h2, http/1.1
2.) WS: http/1.1
3.) GRPC: h2

DETAIL Port Server (Pilih salah satu, Sesuaikan dengan bug masing masing):
1.) TLS : 443, 8443, 8880
2.) HTTP/nonTLS : 80, 2082, 2083, 3128, 8080
3.) Outline : 1080

DETAIL AKUN lain lain, WebSocket, FLOW dan SERVICENAME GRPC:

🔑 Trojan 
a.) path WS: /trojan
b.) path WS Antiads: /trojan-antiads
c.) path WS Anti ADS&PORN: /trojan-antiporn
d.) serviceName GRPC: trojan-service

🔑 VMess
a.) path WS: /vmess atau /terserah/vmess
b.) path TCP Header: /vmess-tcp
c.) path WS Antiads: /vmess-antiads
d.) path WS Anti ADS&PORN: /vmess-antiporn
e.) serviceName GRPC: vmess-service

🔑 VLess
a.) Flow TCP: xtls-rprx-vision
b.) path WS: /vless
c.) path WS Antiads: /vless-antiads
d.) path WS Anti ADS&PORN: /vless-antiporn
e.) serviceName GRPC: vless-service

🔑 ShadowSocks 
a.) path WS: /shadowsocks
b.) path TCP Header: /ss-tcp
c.) path WS Antiads: /shadowsocks-antiads
d.) path WS Anti ADS&PORN: /shadowsocks-antiporn
e.) serviceName GRPC: shadowsocks-service

Config URL :

-==============================-
1.) Trojan-TCP TLS 
${trojanlink1}

2.) Trojan-WS TLS 
${trojanlink2}

3.) Trojan-WS nonTLS 
${trojanlink3}

4.) Trojan-GRPC TLS 
${trojanlink4}

5.) VLess-TCP REALITY TLS
${xtls}

6.) VLess-WS TLS 
${vlesslink1}

7.) VLess-WS nonTLS 
${vlesslink2}

8.) VLess-GRPC TLS 
${vlesslink3}

9.) VMess-WS TLS
${vmesslink1}

10.) VMess-WS nonTLS
${vmesslink2}

11.) VMess-GRPC TLS 
${vmesslink3}

12.) Shadowsocks-Outline TCP/UDP
${linkss1}

13.) Shadowsocks-WS TLS 
${linkss2}

14.) Shadowsocks-WS nonTLS 
${linkss3}

15.) Shadowsocks-GRPC TLS 
${linkss4}

-==============================-

Format Openclash : 

1.) Trojan-TCP TLS 
- name: TrojanTCP_${user}
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  alpn:
   - h2
  skip-cert-verify: true

2.) Trojan-WS TLS
- name: TrojanWS_${user}
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  alpn:
  - http/1.1
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/trojan" # selain path ini ada /trojan-antiads atau /trojan-antiporn 

3.) Trojan-GRPC TLS
- name: TrojanGRPC_${user}
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  alpn:
   - h2
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-service
	
4.) VMess-WS TLS
- name: VmessWS_${user}
  server: ${domain}
  port: 443
  type: vmess
  uuid:  ${uuid}
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  alpn:
   - http/1.1
  network: ws
  ws-opts:
    path: /vmess # selain path ini ada path /vmess-antiads atau /vmess-antiporn
    headers:
      Host: ${domain}
  udp: true

5.) VMess-WS nonTLS
- name: VmessWS_${user}
  server: ${domain}
  port: 80
  type: vmess
  uuid:  ${uuid}
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: ${domain}
  alpn:
   - http/1.1
  network: ws
  ws-opts:
    path: /vmess # selain path ini ada path /vmess-antiads atau /vmess-antiporn
    headers:
      Host: ${domain}
  udp: true

6.) VMess-GRPC TLS 
- name: VmessGRPC_${user}
  type: vmess
  server: ${domain}
  port: 443
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  network: grpc
  tls: true
  servername: ${domain}
  alpn:
   - h2
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: vmess-service
	
7.) VLess-TCP REALITY TLS 
- name: VlessReality_${user}
  type: vless
  server: ${domain}
  port: 443
  uuid: ${uuid}
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: static-web.prod.vidiocdn.com
  alpn:
   - h2
   - http/1.1
  reality-opts:
    public-key: M1PTcxApfZYmc8mbUUdMncKejBxZbjEwHGEl68zjlWU
    short-id: 87ae7e1887f2bd1e
  client-fingerprint: chrome

8.) VLess-WS TLS 
- name: VlessWS_${user}
  type: vless
  server: ${domain}
  port: 443
  uuid: ${uuid}
  udp: true
  tls: true
  network: ws
  client-fingerprint: chrome
  servername: ${domain}
  alpn:
   - http/1.1
  skip-cert-verify: true
  ws-opts:
    path: "/vless" # selain path ini ada /vless-antiads atau /vless-antiporn 
    headers:
      Host: ${domain}

9.) VLess-WS nonTLS
- name: VlessWS_${user}
  type: vless
  server: ${domain}
  port: 80
  uuid: ${uuid}
  udp: true
  tls: false
  network: ws
  client-fingerprint: chrome
  alpn:
   - http/1.1
  skip-cert-verify: true
  ws-opts:
    path: "/vless" # selain path ini ada /vless-antiads atau /vless-antiporn
    headers:
      Host: ${domain}

10.) VLess-GRPC TLS
- name: VlessGRPC_${user}
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  network: grpc
  udp: true
  tls: true
  servername: example.com
  alpn:
   - h2
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: vless-service

11.) VLess-GRPC REALITY TLS
- name: VLessRGRPC_${user}
  type: vless
  server: ${domain}
  port: 443
  uuid: ${uuid}
  udp: true
  xudp: true
  skip-cert-verify: true
  tls: true
  client-fingerprint: chrome
  servername: www.spotify.com
  network: grpc
  grpc-opts:
    grpc-service-name: vless-reality-service
  reality-opts:
    public-key: M1PTcxApfZYmc8mbUUdMncKejBxZbjEwHGEl68zjlWU
    short-id: 87ae7e1887f2bd1e
  ip-version: dual
  tfo: false
  smux:
    enabled: false
	
12.) Shadowsocks-Outline TCP/UDP
- name: SSOutline_${user}
  type: ss
  server: ${domain}
  port: 1080
  cipher: aes-128-gcm
  password: ${uuid}
  udp: true

13.) Shadowsocks-WS TLS
- name: SSWS_${user}
  type: ss
  server: ${domain}
  port: 443
  cipher: aes-128-gcm
  password: ${uuid}
  plugin: v2ray-plugin
  plugin-opts:
    mode: websocket
    host: ${domain}
    tls: true
    skip-cert-verify: true
    path: "/shadowsocks" # selain path ini ada /shadowsocks-antiads atau /shadowsocks-antiporn
    mux: false

14.) Shadowsocks-WS nonTLS
- name: SSWS_${user}
  type: ss
  server: ${domain}
  port: 80
  cipher: aes-128-gcm
  password: ${uuid}
  plugin: v2ray-plugin
  plugin-opts:
    mode: websocket
    host: ${domain}
    tls: false
    skip-cert-verify: true
    path: "/shadowsocks" # selain path ini ada /shadowsocks-antiads atau /shadowsocks-antiporn
    mux: false

SELALU PATUHI PERATURAN SERVER DAN TERIMA KASIH SUDAH MEMILIH LINGVPN 🙏

CONTACT WA : https://wa.me/6283129611215
TELEGRAM CHANNEL : https://t.me/LingVPN
TELEGRAM GROUP : https://t.me/LingVPN_Group" > "/var/www/html/link-$user.conf"
echo -e "### all $user $exp2" >> /var/lib/marzban/akun-allvpn.conf
clear
echo -e ""
echo -e "=======-XRAY-ALLVPN-======="
echo -e ""
echo -e "Remarks: ${user}"
echo -e "Domain: ${domain}"
echo -e "Quota: ${gb} GB"
echo -e "Reset Quota Strategy: ${reset_strategy}"
echo -e "-==============================-"
echo -e "password/uuid: ${uuid}"
echo -e "security: auto"
echo -e "allowInsecure: true"
echo -e "-==============================-"
echo -e "List VPN: "
echo -e "1.) Trojan (TCP, WS, GRPC)"
echo -e "2.) VLess (TCP REALITY, WS, GRPC)"
echo -e "3.) VMess (TCP HEADER, WS, GPPC)"
echo -e "4.) ShadowSocks (Outline, TCP HEADER, WS, GRPC)"
echo -e "-==============================-"
echo -e "Untuk detail lengkap, bisa kalian download file dibawah ini"
echo -e "Link URL Config : https://${domain}/link-$user.conf"
echo -e "-==============================-"
echo -e "Link Subscription : https://${domain}${subs}"
echo -e "================================="
echo -e "Expired On: ${exp2}"
rm -r /tmp/${user}_all.json

